context:
  version: 0.6.7

package:
  name: code-minimap
  version: ${{ version }}

source:
  url: https://github.com/wfxr/code-minimap/archive/v${{ version }}.tar.gz
  sha256: 9c16d269c83a628d38ce0e02f2759b5aa6d55d81d20f4f30383191d365e53b73

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - code-minimap --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: High performance code minimap generator
  homepage: https://github.com/wfxr/code-minimap
  repository: https://github.com/wfxr/code-minimap

extra:
  recipe-maintainers:
    - danielnachun
